# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'rnfirebasetest' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for rnfirebasetest
  pod 'Firebase/Core', '~> 5.20.2'
  pod 'Firebase/DynamicLinks', '~> 5.20.2'

  target 'rnfirebasetestTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

post_install do |installer|
  # This fixes the problems with headers not found
  system("mkdir -p Pods/Headers/Public/FirebaseCore && cp Pods/FirebaseCore/Firebase/Core/Public/* Pods/Headers/Public/FirebaseCore/")
end
